### PR TITLE
Add Woonzeker Rentals parser 

### PR DESCRIPTION
**Pull request by Rafaeltheraven**
Woonzeker Rentals is a rental service in Den Haag and Rotterdam. This PR adds a parser for them.

Important to note is that in the UI you can't see the house number, but it is defined in the URL.. I use a regex to get the various parts out of the URL which I have validated using regex101. The regex is as follows:

`/aanbod/([^/]+)/(.*)-([0-9]+)(-[a-zA-Z0-9]+)?`

### CODE REVIEW

**Comment by wtfloris** [comment]
Hey, thanks for contributing!

I don't seem to be able to find any divs with the class `property` in the response from `https://woonzeker.com/aanbod`. Are you using this endpoint as well or is it a different URL?

Let me know!

**Comment by Rafaeltheraven** [comment]
I'm using the same endpoint. I can see divs with the class `property`, they are inside each `property-cards__single` which is inside `property-cards`. I have attached a screenshot.

image

**Comment by wtfloris** [comment]
Interesting, I can also find them manually, looks like the ctrl+F function in my browsers' inspector doesn't work that well.

However, when running the BeautifulSoup line from the commit on the response I get an empty list:

```
>>> url
'https://woonzeker.com/aanbod'
>>> r = requests.get(url)
>>> results = BeautifulSoup(r.content, "html.parser").find_all("div", class_="property")
>>> results
[]
```

I've also tried including headers from a real browser request but that doesn't seem to work. I wonder if it's some kind of rendering/script thing? Do you get results when you run the above snippet?

**Comment by Rafaeltheraven** [comment]
Interesting, I also get `[]` when running in python. Will investigate

**Comment by Rafaeltheraven** [comment]
They seem to be dumping a block of JSON with **all** the data in there in the initial request. It should be possible to get it out of there, but may get a bit complicated

**Comment by wtfloris** [comment]
Yeah I saw the same, if you dump it in a text editor and replace \n with newlines you get some raw text format of the page:

```

Very luxurious apartment with high-quality finishes, located in the heart of The Hague\'s city center, a vibrant and lively area with a unique blend of historical charm and modern comfort. The neighborhood offers everything you need within walking distance: from luxury boutiques and cozy cafes to cultural hotspots such as museums and theaters. The streets around Calliopestraat are atmospheric and lively, with a variety of dining options and entertainment venues. Additionally, you benefit from excellent public transportation connections and quick access to Central Station.\

LAYOUT: Entrance at street level, you enter the common area. You take the elevator to the 3rd floor where the apartment is located. Front door to the apartment, entrance to the hallway from which you enter the living room. Steel doors open to the spacious and bright living room of approximately 58 m². Open kitchen equipped with a stove, extractor hood, refrigerator, freezer, combination oven, and dishwasher. Back to the hallway, from where you can access all other rooms. The apartment has two bedrooms of approximately 20 m² and 16 m². The bathroom is equipped with a double rain shower, double sink, and toilet.\

The entire apartment has a herringbone laminate floor, window coverings, light fixtures, furnishings, and is heated by central heating. The washing machine and dryer are located in the laundry room, and the appliances are included.\

FEATURES:\
- Fantastic, luxurious finishes\
- Fully furnished\
- Perfect location in the heart of The Hague\'s city center\

RENTAL PRICE:\
- Excluding gas, water, electricity, internet, and television\
- Including any service charges and furnishings\

RENTAL CONDITIONS:\
- Property is suitable for a maximum of 2 persons\\u002Ffamily\
- Rental term: minimum 1 year + indefinite period\
- Security deposit equal to the (total) monthly rent\
- Housing permit not required\
- No pets allowed\

REQUIREMENTS:\
See under the \\"rental conditions\\" tab which documents are required for renting this property.\

*No legal rights can be derived from the above text.\
",location:a,neighborhood:a,building:a,excerpt:"**English text below\
```

Interesting structure to say the least.

**Comment by Rafaeltheraven** [comment]
It's possible to parse properly using this library: https://github.com/Nykakin/chompjs lemme quickly commit something

**Comment by Rafaeltheraven** [comment]
Alright it's pretty complex.

1. Use string finder methods to figure out where the relevant json object is in the raw html
2. Parse it using `chompjs`
3. Use a regex to parse the `slug` field, which seems to be the only field consistently filled in.
4. Hope that `formattedPrice` is actually a number and not just some placeholder.
5. Accept that we have no city or external link, so just use the postal code and main link instead.

**Comment by wtfloris** [comment]
Do I understand correctly that there's no city information at all? Because the location filter works on city names so it's a hard requirement unfortunately.

I suppose we could implement some kind of postal code/city mapping, but that would make this a very complicated (and fragile) setup.

**Comment by Rafaeltheraven** [comment]
I've done a bit more investigating and found that they are using the `nuxt` library. At some point, they load in all data from their server, which calls a function with a bunch of different parameters which returns the js object we found earlier. These's parameters "fill in" the placeholder data in the object and seem to be consistent. 

I've been unable as of now to track down exactly where this function is called (except for the fact that https://www.woonzeker.com/_nuxt/ebcc1e9.js is the only file that contains the city strings). But I have been able to deduce the following mapping:

* `w` -> `'S-Gravenhage`
* `E` -> `Rotterdam`
* `aj` -> `Rijswijk`

With this mapping, we can know at least those two cities. If we were able to find out where the mapping comes from exactly, we would be able to know all the data.

**Comment by wtfloris** [comment]
I think (and this is just my limited JS experience talking so I could very well be wrong) that this is just a way to make JS files more efficient: by “compiling” them and replacing long (human-readable) function and variable names into short strings (like ‘a’), simply to make the files smaller so they’re faster to load. 

This would mean that the mapping could change at any time and it would be a waste of time to try and decipher it :(

I do really appreciate all the effort you put in to crack this one. Love me a fun reverse engineering session, so I hope you’re at least having some fun with it as well!

**Comment by Rafaeltheraven** [comment]
Not sure if it's compilation or obfuscation, but yeah, this is why somehow discovering exactly where these values come from would be the true key, as it would allow us to reconstruct the mappings ourselves (since they are guaranteed to at least be consistent per load). Sadly, the external js files are significantly more complicated than the base and use some sort of javascript magic that I don't fully understand. 

The current version should be functional, but it may be a good idea to wait at least a week to see if the mappings have changed. If I discover the original source of the mappings I'll update here.

**Comment by Rafaeltheraven** [comment]
Right! I've looked at the base html through a deobfuscator (should have done that much earlier) and discovered that it just calls the functions right there with all the data!

The mappings can change whenever, since we now dynamically build a mapper at runtime:
1. Get a comma separated list of all the variable names from the function definition
2. Get a comma separated list of the call arguments (we use a csv reader for this since there may be commas in the input strings)
3. Create a dictionary mapping variable names to their values by index
4. For all values we want, we check first if it is in the dictionary. If it is, we need to take the value from the dictionary. If it is not, we assume that the value wasn't obfuscated and we can use the raw.

Man, scraping is an adventure

**Comment by wtfloris** [comment]
Running in dev, let's see how stable it is! So far it looks good.

One small thing I noticed is that the URLs are saved without encoding special characters, so spaces are just spaces instead of `%20`. It works because the Markdown formatting of the messages handles it, but it would be neater to do it properly and save them in encoded format.

**Comment by wtfloris** [comment]
Hi,

It looks like there is some extra information parsed in the address for some homes:

```
                             url                             |                       address                        
-------------------------------------------------------------+------------------------------------------------------
 https://woonzeker.com/aanbod/Voorburg/van-alphenstraat-61-n | van Alphenstraat 61 4
 https://woonzeker.com/aanbod/Voorburg/van-alphenstraat-61-n | van Alphenstraat 61 false
 https://woonzeker.com/aanbod/Voorburg/van-alphenstraat-61-n | van Alphenstraat 61 B
 https://woonzeker.com/aanbod/Voorburg/van-alphenstraat-61-n | van Alphenstraat 61 Huisvestingsvergunning verplicht
 https://woonzeker.com/aanbod/Voorburg/van-alphenstraat-61-n | van Alphenstraat 61 combimagnetron
 https://woonzeker.com/aanbod/Voorburg/van-alphenstraat-61-n | van Alphenstraat 61 C
```

I'd love to live at "van Alphenstraat 61 combimagnetron" but I don't think that's correct. Any idea where this is coming from?

**Comment by Rafaeltheraven** [comment]
Odd, the address is created from `f"{mapping_or_raw(address['street'])} {mapping_or_raw(address['houseNumber'])} {mapping_or_raw(address['houseNumberExtension'])}".strip()`. It seems like `houseNumberExtension` is probably a parameter, but either the mapping is incorrect or they sometimes store other stuff in there. The strange data like `combimagnetron` is used elsewhere in the json to specify various properties.

Annoyingly, it seems to be dumping everything into the extension field **except** for the actual extension (which should be `N`).

**Comment by Rafaeltheraven** [comment]
I see what is happening lmao, The house number extension is `N`, which is **also** a provided parameter. As such, we first look up if any meaning is assigned to the variable `N`, which is `combimagnetron` and then we assume that to be the housenumber extension, as opposed to just taking `N` to be the extension.

Problem is, it's almost impossible to know whether this extension is intended as a string or a variable, since the chompjs parser collapses everything into a string. Luckily, the `slug` which we use for the URL also has the extension encoded into it, so we could use a regex to extract it from there (like I did in the first version of the parser). If we want to be fancy with formatting and stuff we could maybe compare it to what is stored in the `houseNumberExtension` field but I'm not sure that's worth it

**Comment by Rafaeltheraven** [comment]
We extract the extension from the slug now

**Comment by wtfloris** [comment]
urllib's parse.quote is not meant to parse the entire url, but just the path. This encodes the colon after `https` and breaks the link.

See https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote

**Comment by Rafaeltheraven** [comment]
Oops, forgot to RTFM. Fixed it now.

As a sidenote: it seems Hestia has finally helped me find an appartement, so this may be the last PR I'll make in a while :P

**Pull request merged**
