### PR TITLE
Add atta.nl and ooms.com

### PR DESCRIPTION
**Pull request by OmriSteiner**
I suppose you're manually adding things to the DB running this, so I added the URLs for the GET requests in the commit messages.

### CODE REVIEW

**Comment by wtfloris** [comment]
Awesome, thanks! Yes, I add them to the database manually, not really worth the time to automate (yet!). I added some "how to contribute" instructions a few days ago, but the URL in the commit works fine. I'll run it in the test environment for a few days and see how it behaves.

**Comment by OmriSteiner** [comment]
Yeah, I implemented this a couple of days before you added the instructions, but only got around now to open a PR.

**Comment by wtfloris** [comment]
I've got it running in the test env but I noticed that the ooms.com parser doesn't handle house number additions, this gives us "duplicate" entries when in reality the are different addresses, e.g.:

```
https://ooms.com/wonen/aanbod/korte-haven-133-b-1-schiedam-sm106134           | Korte Haven 133      | Schiedam
 https://ooms.com/wonen/aanbod/korte-haven-133-c-schiedam-sm106133             | Korte Haven 133      | Schiedam
```

Should be easy enough because they have some proper JSON. Feel free to fix it if you have a minute, otherwise I can do it when it's merged!

**Comment by OmriSteiner** [comment]
I pushed a fix.

**Comment by OmriSteiner** [comment]
Hey @wtfloris , any update on this?

**Comment by wtfloris** [comment]
Hi,


The Ooms parser looks fine, but it looks like there are very little homes coming online on Atta (just 5 in total so far). I want to verify that house number additions are parsed correctly but unfortunately we'll just have to wait for one to come online:

```
          address          
---------------------------
 Louise De Colignylaan 428
 Joost Banckertsplaats 247
 Chabotlaan 39
 Tandwielstraat 1093
 Joost Banckertsplaats 156
(5 rows)
```

I'll merge the Ooms parser today!

**Comment by OmriSteiner** [comment]
There are examples with house number additions in the buying section, and they parse fine:

```
In [1]: import hestia

In [2]: import requests

In [3]: resp = requests.get("https://atta.nl/woningaanbod/koopaanbod/")

In [4]: hestia.HomeResults("atta", resp)
Out[4]: [Mathenesserdijk 281 A, Rotterdam (Atta), Beijerlandselaan 121 B01, Rotterdam (Atta), Wattbaan 27 71, Nieuwegein (Atta), Wattbaan 27 61, Nieuwegein (Atta), Fluitstraat 15 D, Rotterdam (Atta), Mathenesserweg 73 C02, Rotterdam (Atta), Agniesestraat 5 B02, Rotterdam (Atta), Agniesestraat 5 A, Rotterdam (Atta), Hilledijk 212 B02, Rotterdam (Atta), Gerrit Jan Mulderstraat 18 A03, Rotterdam (Atta), West-Varkenoordseweg 129 C02, Rotterdam (Atta), Plotinusstraat 35, Rotterdam (Atta), Molenvliet 76, Rotterdam (Atta), Willem Landréplein 32, Schiedam (Atta), Pannekoekstraat 66 D, Rotterdam (Atta), Maastunnelplein 22 B, Rotterdam (Atta), Wattbaan 27 21, Nieuwegein (Atta), Wattbaan 27 20, Nieuwegein (Atta), Pasteursingel 31 B, Rotterdam (Atta), Lange Hilleweg 63 A, Rotterdam (Atta), Pleinweg 180 D, Rotterdam (Atta), Wattbaan 27 33, Nieuwegein (Atta), Wattbaan 27 26, Nieuwegein (Atta), Mathenesserweg 40 A02, Rotterdam (Atta), Windhoek 8, Gouda (Atta)]
```

However, when I went over to the koop page, I realized we don't handle pagination.
How is this handled in other parsers? I don't see anything like that.
I guess we can solve this by changing the GET URL to:
```
https://atta.nl/woningaanbod/huuraanbod/?filter_sort=date
```
That sorts it by date, which should work around the problem.

**Comment by wtfloris** [comment]
Ah that's a great way to test it, looks good indeed.

And yes, pagination is "handled" on most websites by setting the sorting to `newest first`. This means a lot of homes would need to be put online in a 5-minute window in order for Hestia to miss something, that rarely happens.

Will merge this later today.

**Pull request merged**
